Controllers/AnalisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoLaboratorio.Data;
using ProjetoLaboratorio.Models;

namespace ProjetoLaboratorio.Controllers
{
    public class AnalisesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnalisesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Analises
        public async Task<IActionResult> Index()
        {
              return View(await _context.Analises.ToListAsync());
        }

        // GET: Analises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Analises == null)
            {
                return NotFound();
            }

            var analiseModel = await _context.Analises
                .FirstOrDefaultAsync(m => m.Id == id);
            if (analiseModel == null)
            {
                return NotFound();
            }

            return View(analiseModel);
        }

        // GET: Analises/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Analises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao")] AnaliseModel analiseModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(analiseModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(analiseModel);
        }

        // GET: Analises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Analises == null)
            {
                return NotFound();
            }

            var analiseModel = await _context.Analises.FindAsync(id);
            if (analiseModel == null)
            {
                return NotFound();
            }
            return View(analiseModel);
        }

        // POST: Analises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Descricao")] AnaliseModel analiseModel)
        {
            if (id != analiseModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(analiseModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnaliseModelExists(analiseModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(analiseModel);
        }

        // GET: Analises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Analises == null)
            {
                return NotFound();
            }

            var analiseModel = await _context.Analises
                .FirstOrDefaultAsync(m => m.Id == id);
            if (analiseModel == null)
            {
                return NotFound();
            }

            return View(analiseModel);
        }

        // POST: Analises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Analises == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Analises'  is null.");
            }
            var analiseModel = await _context.Analises.FindAsync(id);
            if (analiseModel != null)
            {
                _context.Analises.Remove(analiseModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnaliseModelExists(int id)
        {
          return _context.Analises.Any(e => e.Id == id);
        }
    }
}

Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoLaboratorio.Data;
using ProjetoLaboratorio.Models;

namespace ProjetoLaboratorio.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Clientes.Include(c => c.Convenio);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var clienteModel = await _context.Clientes
                .Include(c => c.Convenio)
                .FirstOrDefaultAsync(m => m.CpfCnpjC == id);
            if (clienteModel == null)
            {
                return NotFound();
            }

            return View(clienteModel);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            ViewData["ConvenioId"] = new SelectList(_context.Convenios, "Id", "Nome");
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CpfCnpjC,TipoPessoa,Nome,Endereco,Cidade,Estado,Telefone,Celular,Email,InscEstRG,NomePropriedade,ConvenioId,DataCadastro")] ClienteModel clienteModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clienteModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConvenioId"] = new SelectList(_context.Convenios, "Id", "Nome", clienteModel.ConvenioId);
            return View(clienteModel);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var clienteModel = await _context.Clientes.FindAsync(id);
            if (clienteModel == null)
            {
                return NotFound();
            }
            ViewData["ConvenioId"] = new SelectList(_context.Convenios, "Id", "Nome", clienteModel.ConvenioId);
            return View(clienteModel);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CpfCnpjC,TipoPessoa,Nome,Endereco,Cidade,Estado,Telefone,Celular,Email,InscEstRG,NomePropriedade,ConvenioId,DataCadastro")] ClienteModel clienteModel)
        {
            if (id != clienteModel.CpfCnpjC)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clienteModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteModelExists(clienteModel.CpfCnpjC))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConvenioId"] = new SelectList(_context.Convenios, "Id", "Nome", clienteModel.ConvenioId);
            return View(clienteModel);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var clienteModel = await _context.Clientes
                .Include(c => c.Convenio)
                .FirstOrDefaultAsync(m => m.CpfCnpjC == id);
            if (clienteModel == null)
            {
                return NotFound();
            }

            return View(clienteModel);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Clientes'  is null.");
            }
            var clienteModel = await _context.Clientes.FindAsync(id);
            if (clienteModel != null)
            {
                _context.Clientes.Remove(clienteModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteModelExists(string id)
        {
          return _context.Clientes.Any(e => e.CpfCnpjC == id);
        }
    }
}

Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoLaboratorio.Data;
using ProjetoLaboratorio.Models;

namespace ProjetoLaboratorio.Controllers
{
    public class PedidosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PedidosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pedidos.Include(p => p.Analise).Include(p => p.TipoAnalise);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedidoModel = await _context.Pedidos
                .Include(p => p.Analise)
                .Include(p => p.TipoAnalise)
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedidoModel == null)
            {
                return NotFound();
            }

            return View(pedidoModel);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            ViewData["AnaliseId"] = new SelectList(_context.Analises, "Id", "Descricao");
            ViewData["TipoAnaliseId"] = new SelectList(_context.TipoAnalise, "TipoAnaliseId", "Descricao");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoId,CpfCnpjC,CpfCnpjS,AnaliseId,TipoAnaliseId,Quantidade,Valor,Observacao,DataEntrada,DataSaida")] PedidoModel pedidoModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedidoModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnaliseId"] = new SelectList(_context.Analises, "Id", "Descricao", pedidoModel.AnaliseId);
            ViewData["TipoAnaliseId"] = new SelectList(_context.TipoAnalise, "TipoAnaliseId", "Descricao", pedidoModel.TipoAnaliseId);
            return View(pedidoModel);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedidoModel = await _context.Pedidos.FindAsync(id);
            if (pedidoModel == null)
            {
                return NotFound();
            }
            ViewData["AnaliseId"] = new SelectList(_context.Analises, "Id", "Descricao", pedidoModel.AnaliseId);
            ViewData["TipoAnaliseId"] = new SelectList(_context.TipoAnalise, "TipoAnaliseId", "Descricao", pedidoModel.TipoAnaliseId);
            return View(pedidoModel);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoId,CpfCnpjC,CpfCnpjS,AnaliseId,TipoAnaliseId,Quantidade,Valor,Observacao,DataEntrada,DataSaida")] PedidoModel pedidoModel)
        {
            if (id != pedidoModel.PedidoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedidoModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoModelExists(pedidoModel.PedidoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnaliseId"] = new SelectList(_context.Analises, "Id", "Descricao", pedidoModel.AnaliseId);
            ViewData["TipoAnaliseId"] = new SelectList(_context.TipoAnalise, "TipoAnaliseId", "Descricao", pedidoModel.TipoAnaliseId);
            return View(pedidoModel);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedidoModel = await _context.Pedidos
                .Include(p => p.Analise)
                .Include(p => p.TipoAnalise)
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedidoModel == null)
            {
                return NotFound();
            }

            return View(pedidoModel);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pedidos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pedidos'  is null.");
            }
            var pedidoModel = await _context.Pedidos.FindAsync(id);
            if (pedidoModel != null)
            {
                _context.Pedidos.Remove(pedidoModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoModelExists(int id)
        {
          return _context.Pedidos.Any(e => e.PedidoId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoLaboratorio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/litera.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoLaboratorio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
          <nav class="navbar navbar-expand-lg bg-success justify-content-start" data-bs-theme="dark">
              <div class="container-fluid">

                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Solos & Plantas</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link text-light dropdown-toggle" href="#" id="cadastrosDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Cadastros
                            </a>
                            <div class="dropdown-menu" aria-labelledby="cadastrosDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Solicitantes" asp-action="Index">Solicitantes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Analises" asp-action="Index">Análises</a>
                                <a class="dropdown-item" asp-area="" asp-controller="TipoAnalises" asp-action="Index">Tipo de Análise</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Convenios" asp-action="Index">Convênios</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link text-light dropdown-toggle" href="#" id="cadastrosDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Pedido de Análise
                            </a>
                            <div class="dropdown-menu" aria-labelledby="cadastrosDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Resultados" asp-action="Index">Resultados</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link text-light dropdown-toggle" href="#" id="cadastrosDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Financeiro
                            </a>
                            <div class="dropdown-menu" aria-labelledby="cadastrosDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Financeiro" asp-action="Index">Financeiro</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Relatorios" asp-action="Index">Relatórios</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   <footer class="border-top footer bg-success text-light">
        <div class="container-fluid py-1">
            &copy; 2023 - Laboratório Solos e Plantas - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-light">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

         @await RenderSectionAsync("Scripts", required: false)
</body>
</html>